### DISCUSSION TITLE
How to remove the filter input?

### DISCUSSION THREAD

**Discussion by vigneshksaithal** [codex-team/editor.js#2250] [Q&A] [answered]
I want to remove the filter search input, but couldn't do it using config options. so how can  remove it?

**Comment by neSpecc** [comment, marked as answer]
Why do you want to remove it?

Anyway, you can do it by CSS override:

```css
.ce-toolbox .cdx-search-field {
  display: none;
}
```
