### DISCUSSION TITLE
Is it possible to override the CSS of blocks?

### DISCUSSION THREAD

**Discussion by AdnanKhayyat1** [codex-team/editor.js#2292] [Q&A]
Hi!
I want to add a custom border shadow to every type of block element. I'm currently building an app on React and have EditorJS as part of my npm dependency library. Is there a way to customize the styling of all blocks?

Thanks!

**Comment by alinceDev** [comment]
Hi,

Yes, with CSS, like this :
```css
.ce-block {
     box-shadow: ...;
}
/* or */ 
.ce-block__content
 {
     box-shadow: ...;
}
/* or */
 .cdx-block {
     box-shadow: ...;
} 
 ```
