### DISCUSSION TITLE
How do you style the basic editor?

### DISCUSSION THREAD

**Discussion by niels-numbers** [codex-team/editor.js#2420] [Q&A]
On the website, the content area of the editor has some shadow and stands out:

![image](https://github.com/codex-team/editor.js/assets/1765602/8b1bc261-618e-4249-9432-11a56586fdec)

In my simple example of the editor, I just see a plain white page:

```html
<!DOCTYPE html>
<html>
<head>
    <title>Editor.js Example</title>
</head>
<body >
<div id="editorjs" ></div>

<script src="https://cdn.jsdelivr.net/npm/@editorjs/editorjs@latest"></script>
<script src="https://cdn.jsdelivr.net/npm/@editorjs/header@latest"></script>
<script src="https://cdn.jsdelivr.net/npm/@editorjs/paragraph@latest"></script>
<script src="https://cdn.jsdelivr.net/npm/@editorjs/image@latest"></script>

<script>
    var editor = new EditorJS({
        holder: 'editorjs',
        tools: {
            header: Header,
            paragraph: Paragraph,
            image: {
                class: ImageTool,
                config: {
                    endpoints: {
                        byFile: 'http://localhost:8008/uploadFile',
                        byUrl: 'http://localhost:8008/fetchUrl',
                    }
                }
            }
        },
    });
</script>
</body>
</html>
```

![image](https://github.com/codex-team/editor.js/assets/1765602/ee487f1e-9249-44d4-a339-34a41506c2a1)

Do you have some default CSS that applies a minimalistic styling, so at least the content area sticks out a little bit? When I change body bg, the content area bg changes as well.

**Comment by KhaledAylii** [comment]
There seems to be a bunch of classes in css, I just override them globally. For me I wanted the icons to be white in a dark mode and the input text as well by default to be white.

Here's my `editor.css` file that I globally apply

```css
.ce-block {
  padding-left: 2px;
  padding-right: 2px;
}

.ce-toolbar__plus,
.ce-toolbar__settings-btn,
.ce-paragraph {
  color: white !important;
}
.ce-toolbar__plus:hover,
.ce-toolbar__settings-btn:hover {
  color: #333 !important;
}

```
