### ISSUE TITLE
Can the editor be stretched❓

### ISSUE THREAD

**Issue by afgallo** [codex-team/editor.js#1412]
**Question**

Is it possible for the entire editor to be stretched i.e. take up the entire space of the parent element?

**Context**

I know it appears to be possible to stretch on a per-block basis but I'd like to have the entire editor stretched.

Thank you!

**Comment by neSpecc** [comment]
You can override some editor styles:

```css
.ce-block__content, 
.ce-toolbar__content {
   max-width: none;
}
```
