### ISSUE TITLE
💡Dark Mode for Editor.JS 

### ISSUE THREAD

**Issue by KShivendu** [codex-team/editor.js#1537]
1. Describe a problem.
Many of the modern applications now support dark mode and since editor.js is getting popular, It would be fantastic to have a ready-to-use dark mode configuration.

2. Describe the solution you'd like. 
```
const editor = new EditorJS({
  // ...
  theme: 'dark'
})
```
We can decide the colors as we move ahead.

**Comment by mrspence** [comment]
This would be a fantastic addition to this issue from November - https://github.com/codex-team/editor.js/issues/822

Essentially the option to import editor JS without any styles would be really useful, so we can avoid duplicate code / overriding code.

_P.S - not sure if I've yet dropped an issue on Editor.JS, so I'd just like to say this codebase is one I avidly follow updates and respect. Thank-you for building such a brilliant ecosystem! Some day I hope to donate or contribute if I get time, but for now I want to publicly say thank-you! 👋🙌_

**Comment by neSpecc** [comment]
Something like that? Made in 2 mins by custom style overrides.

![photo_2021-02-16_23-59-29](https://user-images.githubusercontent.com/3684889/108120951-16dd7080-70b3-11eb-8252-e4a067e1fd96.jpg)

**Comment by KShivendu** [comment]
Looks great. That's what I was talking about. Now I think it's better if we leave it up to the developers to set their colors using CSS classes provided in [Core Styles API](https://editorjs.io/styles).

**Comment by Eonasdan** [comment]
Here's what I ended up with. Main body background color is `#171717` and font color is white.

![image](https://user-images.githubusercontent.com/1006516/131918900-71d17c1b-e940-4af5-a63f-bf22f983d4d6.png)


```css
.ce-block--selected .ce-block__content,
.ce-inline-toolbar,
.codex-editor--narrow .ce-toolbox,
.ce-conversion-toolbar,
.ce-settings,
.ce-settings__button,
.ce-toolbar__settings-btn,
.cdx-button,
.ce-popover,
.ce-toolbar__plus:hover {
  background: #007991;
  color: inherit;
}

.ce-inline-tool,
.ce-conversion-toolbar__label,
.ce-toolbox__button,
.cdx-settings-button,
.ce-toolbar__plus {
  color: inherit;
}

::selection {
  background: #439a86;
}

.cdx-settings-button:hover,
.ce-settings__button:hover,
.ce-toolbox__button--active,
.ce-toolbox__button:hover,
.cdx-button:hover,
.ce-inline-toolbar__dropdown:hover,
.ce-inline-tool:hover,
.ce-popover__item:hover,
.ce-toolbar__settings-btn:hover {
  background-color: #439a86;
  color: inherit;
}

.cdx-notify--error {
  background: #fb5d5d !important;
}

.cdx-notify__cross::after,
.cdx-notify__cross::before {
  background: white;
}
```

**Comment by fitterfizzle** [comment]
> Something like that? Made in 2 mins by custom style overrides.
> 
> ![photo_2021-02-16_23-59-29](https://user-images.githubusercontent.com/3684889/108120951-16dd7080-70b3-11eb-8252-e4a067e1fd96.jpg)

Could you please share your CSS?

**Comment by fitterfizzle** [comment]
Friendly bump @neSpecc

**Comment by Eonasdan** [comment]
@fitterfizzle copy what I posted and change the colors

**Comment by fitterfizzle** [comment]
> ```css
>     background: #007991;
> ```

Thanks much appreciated. 

I tried creating a .css file with your suggestions but sadly still doesn't really look as it should.

![image](https://user-images.githubusercontent.com/96863959/204823594-828dcc50-bc6d-4ee8-b9e5-f87260d35a3f.png)

Moreover I need also some way to change the applied classes dynamically as my application supports changing between light and dark mode on the fly.

**Comment by Eonasdan** [comment]
I updated my previous comment. I must have fixed the other styles at some point. As far as a light/dark, media queries could do that based on the users preferred theme. If you have a toggle button, something like this might help: https://css-tricks.com/updating-a-css-variable-with-javascript/

**Comment by homocodian** [comment]
> Something like that? Made in 2 mins by custom style overrides.
> 
> ![photo_2021-02-16_23-59-29](https://user-images.githubusercontent.com/3684889/108120951-16dd7080-70b3-11eb-8252-e4a067e1fd96.jpg)

Can share these styles with us?

**Comment by MussaratAziz** [comment]
@neSpecc  can you please share the css please.

**Comment by geekyayush** [comment]
Friendly bump good sir @neSpecc 
I'd appreciate it if you share the custom CSS for this design: https://github.com/codex-team/editor.js/issues/1537#issuecomment-780115551

**Comment by MussaratAziz** [comment]
> Friendly bump good sir @neSpecc I'd appreciate it if you share the custom CSS for this design: [#1537 (comment)](https://github.com/codex-team/editor.js/issues/1537#issuecomment-780115551)

most probably @neSpecc  doesnt want to share @geekyayush

**Comment by geekyayush** [comment]
> most probably @neSpecc doesnt want to share @geekyayush

If it's true, it's really sad. :(
I wish I was skilled enough to do custom CSS. Just stuck in the backend at the moment lol.

**Comment by anuragrao04** [comment]
@neSpecc please do post if you're willing to share the styles, and if yes- please do post the styles as well.

**Comment by anuragrao04** [comment]
I put together some CSS and it looks decent:

![image](https://github.com/codex-team/editor.js/assets/77329899/8ff7d059-050b-4d8d-a1f8-079cc6fc6e61)

Here's the CSS:

```css
.cdx-block,
.ce-header,
.inlineToolButton,
.ce-toolbar__plus,
.ce-toolbar__settings-btn,
.ce-popover__search {
  background-color: #2b2b2b;
  color: white;
}

.ce-toolbar__plus:hover,
.ce-toolbar__settings-btn:hover,
.cdx-loader,
.cdx-button {
  color: white;
  background-color: #262626;
}

.cdx-button:hover {
  background-color: #2f2f2f;
}

.ce-popover,
.ce-popover-item,
.ce-popover-item__icon,
.ce-popover-items,
.ce-popover-item:hover {
  --color-background-item-hover: #2f2f2f;
  background-color: #262626;
  color: white;
  border: none;
}
```

**Comment by geekyayush** [comment]
> I put together some CSS and it looks decent

Dude, who are you? Did god send you to help me (a fellow developer)?

Thank you so much.

**Comment by neSpecc** [comment]
Hi there. I remember this request. 

I can't share exact those styles from my screenshot since they were made just to experiment with how easily anyone can override any Editor style. I made them in DevTools and did not save them.

I suppose you are mostly interested in a set of CSS selectors to override, not in colors itself. You can [begin with these classes](https://github.com/codex-team/editor.js/blob/next/public/assets/demo.css#L346) from our example page, and then just use your DevTools inspector to find what style you also want to override.

More important for us is to refactor Editor styles at all. I'm planning to rewrite styles by exposing a set of CSS variables that you can easily override and tune. Not only colors but all main tokens (sizes, roundings, font, etc).

At the moment I'm also working on our Design System, which will be a separate package including theming, colors, and components. It could be used by Editor and 3rd party tools as well.

**Comment by longvo00221** [comment]
.ce-block--selected .ce-block__content,
.ce-inline-toolbar,
.codex-editor--narrow .ce-toolbox,
.ce-conversion-toolbar,
.ce-settings,
.ce-settings__button,
.ce-toolbar__settings-btn,
.cdx-button,
.ce-popover,
.ce-toolbar__plus:hover {
  background: #0000;
  color: inherit;
}

.ce-inline-tool,
.ce-conversion-toolbar__label,
.ce-toolbox__button,
.cdx-settings-button,
.ce-toolbar__plus {
  color: inherit;
}

::selection {
  background: #000;
}

.cdx-settings-button:hover,
.ce-settings__button:hover,
.ce-toolbox__button--active,
.ce-toolbox__button:hover,
.cdx-button:hover,
.ce-inline-toolbar__dropdown:hover,
.ce-inline-tool:hover,
.ce-popover__item:hover,
.ce-toolbar__settings-btn:hover {
  background-color: #aaaaaa;
  color: inherit;
}

.cdx-notify--error {
  background: #fb5d5d !important;
}

.cdx-notify__cross::after,
.cdx-notify__cross::before {
  background: white;
}

.dark .ce-inline-toolbar,
.dark .codex-editor--narrow .ce-toolbox,
.dark .ce-conversion-toolbar,
.dark .ce-settings,
.dark .ce-settings__button,
.dark .ce-toolbar__settings-btn,
.dark .cdx-button,
.dark .ce-popover,
.dark .ce-toolbar__plus:hover {
  background: #fff;
  color: #000;
}

.dark .ce-inline-tool,
.dark .ce-conversion-toolbar__label,
.dark .ce-toolbox__button,
.dark .cdx-settings-button,
.dark .ce-toolbar__plus {
  color: #616161;
}

.dark ::selection {
  background: #4d4d4d;
}

.dark .cdx-settings-button:hover,
.dark .ce-settings__button:hover,
.dark .ce-toolbox__button--active,
.dark .ce-toolbox__button:hover,
.dark .cdx-button:hover,
.dark .ce-inline-toolbar__dropdown:hover,
.dark .ce-inline-tool:hover,
.dark .ce-popover__item:hover,
.dark .ce-toolbar__settings-btn:hover {
  background-color: #4d4d4d;
  color: #fff;
}

.dark .cdx-notify--error {
  background: #fb5d5d !important;
}

.dark .cdx-notify__cross::after,
.dark .cdx-notify__cross::before {
  background: #1a1a1a;
} 


this is the css for dark and light theme nextjs shadcn

**Comment by Miguel-Domingos** [comment]
I was working with the Editor yesterday and I was looking for dark mode, I saw that more people were in the same situation.
So, I've decided to solve and publish my code (style), soon I'll be creating a configuration mode to support dark mode, for now, if you want to use dark mode, you can find style code in my portfolio [here](https://github.com/Miguel-Domingos/Editorjs-Dark) 

See the result, bellow:

**Light mode**
![light](https://github.com/codex-team/editor.js/assets/79005738/62080f8c-4799-4072-86a7-34206106b504)

**Dark mode**
![dark](https://github.com/codex-team/editor.js/assets/79005738/8685d273-3cb0-4045-b8a4-c83f3cea1692)

**Comment by manuelcunga** [comment]
> I was working with the Editor yesterday and I was looking for dark mode, I saw that more people were in the same situation. So, I've decided to solve and publish my code (style), soon I'll be creating a configuration mode to support dark mode, for now, if you want to use dark mode, you can find style code in my portfolio [here](https://github.com/Miguel-Domingos/Editorjs-Dark)
> 
> See the result, bellow:
> 
> **Light mode** ![light](https://private-user-images.githubusercontent.com/79005738/327714169-62080f8c-4799-4072-86a7-34206106b504.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3Mzc3MjEsIm5iZiI6MTcxNDczNzQyMSwicGF0aCI6Ii83OTAwNTczOC8zMjc3MTQxNjktNjIwODBmOGMtNDc5OS00MDcyLTg2YTctMzQyMDYxMDZiNTA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDExNTcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0MzFlMDk0ZGZjZDQ2OTFhMWRkYjVmYmQ5NTRmMDQ1YTFhYmM4MjMyNzMxNDc5YTNhYWE2NWIxYjM0ZDk4MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YSQufgbbmPmXszr1nyFmJSgwwA42WO-vguY7ZWkVvHU)
> 
> **Dark mode** ![dark](https://private-user-images.githubusercontent.com/79005738/327714243-8685d273-3cb0-4045-b8a4-c83f3cea1692.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3Mzc3MjEsIm5iZiI6MTcxNDczNzQyMSwicGF0aCI6Ii83OTAwNTczOC8zMjc3MTQyNDMtODY4NWQyNzMtM2NiMC00MDQ1LWI4YTQtYzgzZjNjZWExNjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDExNTcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyYWFhZDNmZDNiZjFlYzU1MjQyNjUyMTk5NzVkNTY5ZGUzYTE2ZjFhOGQwNzlmMTc3ZDc0MzAyODZmNWVkMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.okT62GrKWSGBQnLPyob4XtJK8JyszDSBJunQqDybyck)

Man you´re Hero

**Comment by vipertecpro** [comment]
![Screenshot 2024-09-20 at 1 11 43 PM](https://github.com/user-attachments/assets/b7b3b38b-88ad-4d09-be6b-2c1bb450bf2d)

I really tried my best there, please give me feedback on this, i will work on it's padding and hover effect later on

```
@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
    --padding: 10px;
    --max-height: 300px;
    --color-border: #ccc;
    --width: 200px;
    --border-radius: 5px;
    --color-shadow: rgba(0, 0, 0, 0.1);
    --popover-top: 50px;
    --popover-left: 50px;
    --color-background: #fff;
    --color-background-dark: rgba(0, 0, 0, 0.4);
}

/* Default light mode styles */
.cdx-block,
.ce-header,
.inlineToolButton,
.ce-toolbar__plus,
.ce-toolbar__settings-btn,
.ce-popover__search {
    @apply bg-white text-black;
}

/* Dark mode styles */
.dark .cdx-block,
.dark .ce-header,
.dark .inlineToolButton,
.dark .ce-toolbar__plus,
.dark .ce-toolbar__settings-btn,
.dark .ce-popover__search {
    @apply bg-gray-800 text-white;
}

.dark .ce-toolbar__plus:hover,
.dark .ce-toolbar__settings-btn:hover,
.dark .cdx-loader,
.dark .cdx-button {
    @apply text-white bg-gray-700;
}

.dark .cdx-button:hover {
    @apply bg-gray-600;
}

.dark .ce-popover,
.dark .ce-popover-item,
.dark .ce-popover-item__icon,
.dark .ce-popover-items,
.dark .ce-popover-item:hover {
    @apply bg-gray-700 text-white border-none;
}

.ce-popover--opened > .ce-popover__container {
    @apply opacity-100 pointer-events-auto border;
    padding: var(--padding);
    max-height: var(--max-height);
    animation: panelShowing .1s ease;
    border-color: var(--color-border);
}

.ce-popover__container {
    @apply overflow-hidden box-border absolute flex flex-col z-10 opacity-0 pointer-events-none p-0 border-none;
    min-width: var(--width);
    width: var(--width);
    max-height: var(--max-height);
    border-radius: var(--border-radius);
    box-shadow: 0 3px 15px -3px var(--color-shadow);
    left: var(--popover-left);
    top: var(--popover-top);
    background: var(--color-background);
}

.dark .ce-popover__container {
    background: var(--color-background-dark);
}

/* Light mode scrollbar */
.ce-popover__items::-webkit-scrollbar {
    width: 4px;
}

.ce-popover__items::-webkit-scrollbar-thumb {
    background-color: #ccc;
    border-radius: 10px;
}

/* Dark mode scrollbar */
.dark .ce-popover__items::-webkit-scrollbar {
    width: 4px;
}

.dark .ce-popover__items::-webkit-scrollbar-thumb {
    background-color: #555;
    border-radius: 10px;
}

.dark .ce-inline-tool svg {
    color: white;
}

.dark .ce-inline-tool:hover svg {
    color: var(--color-background-dark);
}

```

**Comment by lukajose** [comment]
For those who want shadcn + tailwindcss integration:
![Screen Shot 2024-09-22 at 5 48 33 pm](https://github.com/user-attachments/assets/ba11bd6a-f9ac-46e9-92ba-55a93435bb9f)


```css
.dark .ce-popover,
.dark .ce-popover-item,
.dark .ce-popover-item__icon,
.dark .ce-popover-items,
.dark .ce-popover__container
.dark .ce-popover-item:hover {
  --color-background-item-hover: hsl(var(--background));
  background-color: hsl(var(--background));
  border-color: hsl(var(--border));
  background: hsl(var(--background));
}
.dark .ce-popover__container {
  background: hsl(var(--background));
}


.dark .ce-popover--opened>.ce-popover__container {
  border: 1px solid hsl(var(--border));
}

.dark .ce-popover-item-separator__line {
  border: 1px solid hsl(var(--border));
}

.dark .ce-toolbar__plus,
.dark .ce-toolbar__settings-btn,
.dark .ce-popover-item__title,
.dark .ce-inline-tool
.dark .ce-inline-tool--link
.dark .ce-popover-item__icon {
  color: hsl(var(--foreground));
}

.dark .cdx-search-field.ce-popover__search {
  background-color: hsl(var(--muted) / 0.3);
  border-color: hsl(var(--border));
}

.dark .cdx-search-field__input {
  color: hsl(var(--foreground));
}

.dark .cdx-block,
.dark .ce-block {
  color: hsl(var(--foreground));
}

.dark .ce-inline-toolbar,
.dark .ce-conversion-tool__icon,
.dark .ce-popover-item__icon,
.dark .tc-popover__item-icon {
  color: hsl(var(--foreground));
  background-color: hsl(var(--background));
  border-color: hsl(var(--border));
}

.dark .ce-popover,
.dark .ce-conversion-toolbar,
.dark .ce-inline-toolbar,
.dark .tc-popover {
  background-color: hsl(var(--popover));
  border-color: hsl(var(--border));
  box-shadow: 0 3px 15px -3px hsl(var(--border) / 0.2);
}

.dark .ce-inline-tool {
  color: hsl(var(--color-text-primary));
}

.dark .ce-inline-tool:hover,
.dark .ce-inline-toolbar__dropdown:hover,
.dark .ce-toolbar__plus:hover,
.dark .ce-toolbar__settings-btn:hover,
.dark .ce-conversion-tool:hover,
.dark .ce-popover-item:hover {
  background-color: hsl(var(--accent) / 0.2);
}

.dark *::selection,
.dark .ce-block.ce-block--selected .ce-block__content {
  background-color: hsl(var(--accent) / 0.2);
}

.dark .ce-popover__items {
  scrollbar-color: hsl(var(--border)) hsl(var(--background));
}

/* table class wrapper */
.dark .tc-wrap,
.dark .tc-wrap * {
  --color-border: hsl(var(--border));
  --color-text-secondary: hsl(var(--foreground));
  --color-background: hsl(var(--accent) / 0.2);
  --toggler-dots-color: hsl(var(--accent) / 0.2);
  --toggler-dots-color-hovered: hsl(var(--foreground));
}

@media (max-width: 650px) {
  .dark .ce-toolbar__settings-btn,
  .dark .ce-toolbar__plus {
    background-color: hsl(var(--popover));
    border-color: hsl(var(--border));
    box-shadow: 0 3px 15px -3px hsl(var(--border) / 0.2);
  }
}
```

**Comment by antoniosaints** [comment]
> For those who want shadcn + tailwindcss integration: ![Screen Shot 2024-09-22 at 5 48 33 pm](https://private-user-images.githubusercontent.com/37333424/369672407-ba11bd6a-f9ac-46e9-92ba-55a93435bb9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1NDYzMzIsIm5iZiI6MTcyNzU0NjAzMiwicGF0aCI6Ii8zNzMzMzQyNC8zNjk2NzI0MDctYmExMWJkNmEtZjlhYy00NmU5LTkyYmEtNTVhOTM0MzViYjlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDE3NTM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0YzY4MzU5MzQ0NjhiODU2ZDM3NDZiZGM1OTlkMTM5OGM5MDA3OTUyY2ExNTE5N2UyODIzNTAzMTA0ODI5YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.x1TDZSr3Ym9K_0XVDrkM1pLHIrjofBldBVp2qJBa0yU)
> 
> ```css
> .dark .ce-popover,
> .dark .ce-popover-item,
> .dark .ce-popover-item__icon,
> .dark .ce-popover-items,
> .dark .ce-popover__container
> .dark .ce-popover-item:hover {
>   --color-background-item-hover: hsl(var(--background));
>   background-color: hsl(var(--background));
>   border-color: hsl(var(--border));
>   background: hsl(var(--background));
> }
> .dark .ce-popover__container {
>   background: hsl(var(--background));
> }
> 
> 
> .dark .ce-popover--opened>.ce-popover__container {
>   border: 1px solid hsl(var(--border));
> }
> 
> .dark .ce-popover-item-separator__line {
>   border: 1px solid hsl(var(--border));
> }
> 
> .dark .ce-toolbar__plus,
> .dark .ce-toolbar__settings-btn,
> .dark .ce-popover-item__title,
> .dark .ce-inline-tool
> .dark .ce-inline-tool--link
> .dark .ce-popover-item__icon {
>   color: hsl(var(--foreground));
> }
> 
> .dark .cdx-search-field.ce-popover__search {
>   background-color: hsl(var(--muted) / 0.3);
>   border-color: hsl(var(--border));
> }
> 
> .dark .cdx-search-field__input {
>   color: hsl(var(--foreground));
> }
> 
> .dark .cdx-block,
> .dark .ce-block {
>   color: hsl(var(--foreground));
> }
> 
> .dark .ce-inline-toolbar,
> .dark .ce-conversion-tool__icon,
> .dark .ce-popover-item__icon,
> .dark .tc-popover__item-icon {
>   color: hsl(var(--foreground));
>   background-color: hsl(var(--background));
>   border-color: hsl(var(--border));
> }
> 
> .dark .ce-popover,
> .dark .ce-conversion-toolbar,
> .dark .ce-inline-toolbar,
> .dark .tc-popover {
>   background-color: hsl(var(--popover));
>   border-color: hsl(var(--border));
>   box-shadow: 0 3px 15px -3px hsl(var(--border) / 0.2);
> }
> 
> .dark .ce-inline-tool {
>   color: hsl(var(--color-text-primary));
> }
> 
> .dark .ce-inline-tool:hover,
> .dark .ce-inline-toolbar__dropdown:hover,
> .dark .ce-toolbar__plus:hover,
> .dark .ce-toolbar__settings-btn:hover,
> .dark .ce-conversion-tool:hover,
> .dark .ce-popover-item:hover {
>   background-color: hsl(var(--accent) / 0.2);
> }
> 
> .dark *::selection,
> .dark .ce-block.ce-block--selected .ce-block__content {
>   background-color: hsl(var(--accent) / 0.2);
> }
> 
> .dark .ce-popover__items {
>   scrollbar-color: hsl(var(--border)) hsl(var(--background));
> }
> 
> /* table class wrapper */
> .dark .tc-wrap,
> .dark .tc-wrap * {
>   --color-border: hsl(var(--border));
>   --color-text-secondary: hsl(var(--foreground));
>   --color-background: hsl(var(--accent) / 0.2);
>   --toggler-dots-color: hsl(var(--accent) / 0.2);
>   --toggler-dots-color-hovered: hsl(var(--foreground));
> }
> 
> @media (max-width: 650px) {
>   .dark .ce-toolbar__settings-btn,
>   .dark .ce-toolbar__plus {
>     background-color: hsl(var(--popover));
>     border-color: hsl(var(--border));
>     box-shadow: 0 3px 15px -3px hsl(var(--border) / 0.2);
>   }
> }
> ```

wow, thanks man, i need this

**Comment by pranavmappoli** [comment]
@vipertecpro In which file you added this ? in global.css or any custom css file and imported in editor.tsx ?

**Comment by lukajose** [comment]
Both should work, I did global.

> [@vipertecpro](https://github.com/vipertecpro) In which file you added this ? in global.css or any custom css file and imported in editor.tsx ?

**Comment by kevinwaxi** [comment]
If you happen to look for tailwind v4 compatibility with shadcn(test on vue)

```css
.dark .ce-popover,
.dark .ce-popover-item,
.dark .ce-popover-item__icon,
.dark .ce-popover-items,
.dark .ce-popover__container
.dark .ce-popover-item:hover {
  --color-background-item-hover: var(--accent);
  background-color: var(--accent);
  border-color: var(--popover-foreground);
  background: var(--background);
}
.dark .ce-popover__container {
  background: var(--popover);
}


.dark .ce-popover--opened>.ce-popover__container {
  border: 1px solid var(--border);
}

.dark .ce-popover-item-separator__line {
  border: 1px solid var(--border);
}

.dark .ce-toolbar__plus,
.dark .ce-toolbar__settings-btn,
.dark .ce-popover-item__title,
.dark .ce-inline-tool
.dark .ce-inline-tool--link
.dark .ce-popover-item__icon {
  color: var(--foreground);
}

.dark .cdx-search-field.ce-popover__search {
  background-color: var(--muted) / 0.3;
  border-color: var(--border);
}

.dark .cdx-search-field__input {
  color: var(--foreground);
}

.dark .cdx-block,
.dark .ce-block {
  color: var(--foreground);
}

.dark .ce-inline-toolbar,
.dark .ce-conversion-tool__icon,
.dark .ce-popover-item__icon,
.dark .tc-popover__item-icon {
  color: var(--foreground);
  background-color: var(--background);
  border-color: var(--border);
}

.dark .ce-popover,
.dark .ce-conversion-toolbar,
.dark .ce-inline-toolbar,
.dark .tc-popover {
  background-color: var(--popover);
  border-color: var(--border);
  box-shadow: 0 3px 15px -3px var(--border) / 0.2;
}

.dark .ce-inline-tool {
  color: var(--color-text-primary);
}

.dark .ce-inline-tool:hover,
.dark .ce-inline-toolbar__dropdown:hover,
.dark .ce-toolbar__plus:hover,
.dark .ce-toolbar__settings-btn:hover,
.dark .ce-conversion-tool:hover,
.dark .ce-popover-item:hover {
  background-color: var(--accent);
}

.dark *::selection,
.dark .ce-block.ce-block--selected .ce-block__content {
  background-color: var(--accent) / 0.2;
}

.dark .ce-popover__items {
  scrollbar-color: var(--border) var(--background);
}


.ce-popover-item-html {
    @apply bg-background transition-colors;
}

.dark .ce-popover-item-html {
    @apply bg-popover;
}

.ce-popover-item-html:hover {
    @apply bg-muted;
}

.dark .ce-popover-item-html:hover {
    @apply bg-muted/30;
}

.ce-inline-tool {
    @apply text-foreground transition-colors;
}

.dark .ce-inline-tool {
    @apply text-foreground;
}

.ce-inline-tool--active {
    @apply bg-accent text-accent-foreground;
}

.dark .ce-inline-tool--active {
    @apply bg-accent text-accent-foreground;
}

.dark .ce-inline-tool-input,
.dark .ce-inline-tool-input--showed {
    @apply bg-popover text-popover-foreground;
}


/* table class wrapper */
.dark .tc-wrap,
.dark .tc-wrap * {
  --color-border: var(--border);
  --color-text-secondary: var(--foreground);
  --color-background: var(--accent) / 0.2;
  --toggler-dots-color: var(--accent) / 0.2;
  --toggler-dots-color-hovered: var(--foreground);
}

@media (max-width: 650px) {
  .dark .ce-toolbar__settings-btn,
  .dark .ce-toolbar__plus {
    background-color: var(--popover);
    border-color: var(--border);
    box-shadow: 0 3px 15px -3px var(--border) / 0.2;
  }
}

**Comment by tusshr** [comment]
@lukajose Thanks a lot man!  Saved huge time for rewriting

**Comment by ghost** [comment]
Is there any news to properly support this without us having to rewrite custom css? maybe introducing the notion of a 'theme' or something

**Comment by Miguel-Domingos** [comment]
@flipcard-io as i know, not yet. but i was working working on it on my own

**Comment by beautyfree** [comment]
any news?

**Comment by smir-ant** [comment]
up

**Comment by cainmagi** [comment]
For those who do not want to use tailwindCSS or shadcn or vue, here is an implementation with the pure SCSS:
```scss
:global {
  .editorjs-dark {
    // editor-dark.scss
    // Modified from
    // https://github.com/Miguel-Domingos/Editorjs-Dark

    // SCSS variables
    $editor-bg: #1e1e1e;
    $editor-primary: $editor-bg;
    $editor-text: #e0e0e0;
    $editor-border: #333;
    $editor-accent: #388ae5;
    $editor-hover: rgba(255, 255, 255, 0.2);
    $editor-search-bg: #2c2c2c;
    $editor-search-text: #ccc;

    .ce-popover {
      --color-border: #{$editor-border};
      --color-shadow: rgba(198, 205, 219, 0.1);
      --color-background: #{$editor-bg};
      --color-text-primary: #{$editor-text};
      --color-text-secondary: #{$editor-search-text};
      --color-border-icon: rgba(59, 59, 59, 0.48);
      --color-border-icon-disabled: #222222;
      --color-text-icon-active: #{$editor-accent};
      --color-background-icon-active: rgba(3, 3, 3, 0.1);
      --color-background-item-focus: rgba(34, 186, 255, 0.08);
      --color-shadow-item-focus: rgba(7, 161, 227, 0.08);
      --color-background-item-hover: #{$editor-hover};
      --color-background-item-confirm: #430909;
      --color-background-item-confirm-hover: #561c1c;
    }

    .cdx-list {
      --checkbox-background: #000;
      --color-border: #{$editor-border};
      --color-bg-checked: #1c578a;
      --color-bg-checked-hover: #005bb1;
      --color-tick: #fff;
    }

    .cdx-list-start-with-field {
      background: $editor-bg;
    }

    .ce-toolbar__plus,
    .ce-toolbar__settings-btn,
    .ce-popover-item__title,
    .ce-popover-item__icon {
      color: $editor-text;
    }

    .cdx-search-field.ce-popover__search {
      background-color: $editor-search-bg;
      border-color: $editor-border;
    }

    .cdx-search-field__input {
      color: $editor-search-text;
    }

    .cdx-block,
    .ce-block {
      color: $editor-text;
    }

    .ce-inline-toolbar,
    .ce-conversion-tool__icon,
    .ce-popover-item__icon,
    .tc-popover__item-icon {
      color: $editor-text;
      // background-color: $editor-primary;
      border-color: $editor-border;
    }

    .ce-popover,
    .ce-conversion-toolbar,
    .ce-inline-toolbar,
    .tc-popover {
      background-color: $editor-primary;
      border-color: $editor-border;
      box-shadow: 0 3px 15px -3px $editor-border;
    }

    .ce-inline-tool:hover,
    .ce-inline-toolbar__dropdown:hover,
    .ce-toolbar__plus:hover,
    .ce-toolbar__settings-btn:hover,
    .ce-conversion-tool:hover,
    .ce-popover-item:hover {
      background-color: $editor-hover;
    }

    *::selection,
    .ce-block.ce-block--selected .ce-block__content {
      background-color: $editor-hover;
    }

    .ce-popover__items {
      scrollbar-color: $editor-border $editor-bg;
    }
    /* table class wrapper */
    .tc-wrap,
    .tc-wrap * {
      --color-border: $editor-border;
      --color-text-secondary: $editor-text;
      --color-background: $editor-hover;
      --toggler-dots-color: $editor-hover;
      --toggler-dots-color-hovered: $editor-text;
    }

    @media (max-width: 650px) {
      .ce-toolbar__settings-btn,
      .ce-toolbar__plus {
        background-color: $editor-primary;
        border-color: $editor-border;
        box-shadow: 0 3px 15px -3px $editor-border;
      }
    }
  }
}
```

The above file use `:global` because I import it as a module for bypassing the nonce issues. See the following usage, where `themeMode` is `"light" | "dark"`, and styles are forced to be injected by `void styles`):
```jsx
import React, { useRef, useEffect } from "react";
import clsx from "clsx/lite";
import * as styles from "./index.module.scss";

import EditorJS from "@editorjs/editorjs";

import { useSelector } from "react-redux";
import { RootState } from "../../store";

const ThemedEditor = () => {
  const themeMode = useSelector(
    (state: RootState) => state.appStates.themeMode,
  );
  const editorRef = useRef<EditorJS | null>(null);
  void styles;

  const initializeEditor = async () => {
    if (editorRef.current) {
      return;
    }
    const editor = new EditorJS({
      holder: "editorjs",
    });

    editorRef.current = editor;
  }

  useEffect(() => {
    initializeEditor();

    return () => {
      const destroy = editorRef.current?.destroy;
      if (typeof destroy === "function") {
        destroy();
      }
      editorRef.current = null;
    };
  }, []);

  return (
    <div className={clsx(themeMode === "dark" ? "editorjs-dark" : "")}>
      <div id="editorjs"/>
    </div>
  );
}

export default ThemedEditor;
```
