### ISSUE TITLE
Placeholder text shouldn't dissapear as soon as editor is focused, it should dissappear when the user starts typing

### ISSUE THREAD

**Issue by CamdenSpehl** [codex-team/editor.js#2604]
The placeholder text goes away when the editor is focused, even if it is still blank. It should behave like other inputs, where the placeholder goes away once the user starts typing and not when they click in the box. Maybe there is a way to do this I haven't found yet, but it makes the editor feel much less nice.

I wanted to do this to make the editor feel much ncier on my app

**Comment by etumyan** [comment]
It seems we can achieve such behavior by overriding some CSS.

For an empty editor only:
```css
.ce-block:first-child .ce-paragraph[data-placeholder]:empty::before {
  opacity: 1 !important;
}
```

For all paragraphs:
```css
.ce-paragraph[data-placeholder]:empty::before {
  opacity: 1 !important;
}
```

For other text blocks the solution may be slightly different:
```css
.ce-header[data-placeholder]:empty::before {
  display: block !important;
}
```
